spring:
  data:
    mongodb:
      uri: mongodb+srv://sk1609525_db_user:23ZslgJ8ep4CXyHX@cluster0.zqrmzsb.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal
